version: "3.8"
services:
  web:
    image: php-web-built
    ports:
      - 80:80
    volumes:
      - ${WEB_VOLUME}:/var/www/html/src
      - /var/www/html/src/vendor
      - /var/www/html/src/node_modules

  db:
    image: mysql8-built
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  vendor:
  node_modules:
  db-store:
